[base]
package = ocean
env_name = puffer_boids 
policy_name = Policy
rnn_name = Recurrent

[env]
num_envs = 64
num_boids = 16
margin_turn_factor = 1.0
cohesion_factor = 0.0048
separation_factor = 0.0128
alignment_factor = 0.2

[vec]
num_workers = 2
num_envs = 2
batch_size = auto

[train]
total_timesteps = 100_000_000
; total_timesteps = 80_000_000
gamma = 0.95
learning_rate = 0.025
minibatch_size = 16384

[sweep]
# Protein
method = Carbs
metric = score
goal = maximize
downsample = 10

[sweep.env.margin_turn_factor]
distribution = log_normal
min = 0.01
max = 1.0
mean = 0.5
scale = auto

[sweep.env.cohesion_factor]
distribution = log_normal
min = 0.01
max = 1.0
mean = 0.5
scale = auto

[sweep.env.separation_factor]
distribution = log_normal
min = 0.01
max = 1.0
mean = 0.5
scale = auto

[sweep.env.alignment_factor]
distribution = log_normal
min = 0.01
max = 1.0
mean = 0.5
scale = auto
